public with sharing class ShowNormalAccountController {
/*    public static List<Account> getNormalAccount() {
      return[SELECT Id, Name, DeveloperName, sObjectType FROM RecordType WHERE IsActive = TRUE and DeveloperName = 'Normal'];
    }
    public static List<Account> getSpecialAccount() {
        return[SELECT Id, Name, DeveloperName, sObjectType FROM RecordType WHERE IsActive = TRUE and DeveloperName = 'Normal'];
      }*/
}